APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:0u5aVZSmW37HkrOoseuuc7SirGJph64FDg40h2M889M=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=u430343503_hexamed
DB_USERNAME=u430343503_hexamedcrm
DB_PASSWORD=Mindhuntz@1234

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

STRIPE_KEY=pk_test_51O9lonSIZxXCO0fi44t7bgvI2SrpMzjEkCAdfCCoyEIJPgyFgaGlMJHc6pI9VXgZyVquayEvos2QoljrRiTykUU4000WDN8NLb
STRIPE_SECRET=sk_test_51O9lonSIZxXCO0fi3jmSjf9SlU5hEGbzIr2m5riL8QRW3jo2TddGnGFVlylx0pcSLXebTGxo3LJJu1TiNXvf2q3R00NeK94MUU
